# Generated by Django 4.1 on 2022-08-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
